from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .profile import ProfileError


def _integer(mapping: dict[str, Any], key: str) -> int:
    value = mapping.get(key)
    if not isinstance(value, int) or value < 0:
        raise ProfileError(f"generated adapter input is missing integer {key}")
    return value


def generate_adapter(
    profile: dict[str, Any], abi: dict[str, Any], destination: Path
) -> None:
    if (
        profile.get("schema") != 1
        or abi.get("schema") != 1
        or abi.get("status") != "verified"
    ):
        raise ProfileError(
            "generated adapter requires schema-1 profile and verified ABI"
        )
    if profile.get("executable_sha256") != abi.get("executable_sha256") or profile.get(
        "bds_version"
    ) != abi.get("bds_version"):
        raise ProfileError("profile and ABI describe different executables")
    platform = abi.get("platform")
    if platform not in {"linux-x86_64", "windows-x86_64"}:
        raise ProfileError("generated adapter platform is unsupported")
    sizes = abi.get("sizes", {})
    offsets = abi.get("offsets", {})
    raw_expected = profile.get("expected_prologue_bytes")
    if not isinstance(raw_expected, str):
        raise ProfileError("profile has no expected call bytes")
    try:
        expected = bytes.fromhex(raw_expected)
    except ValueError as exc:
        raise ProfileError("profile expected call bytes are invalid") from exc
    if len(expected) != 5 or expected[0] != 0xE8:
        raise ProfileError("generated adapter target must be one direct five-byte CALL")
    executable_hash = profile["executable_sha256"]
    profile_id = f"bds-{profile['bds_version']}-{platform}-{executable_hash[:16]}"
    byte_values = ", ".join(f"std::byte{{0x{value:02x}}}" for value in expected)
    windows = platform.startswith("windows")
    platform_include = (
        """#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>"""
        if windows
        else """#include <link.h>
#include <unistd.h>"""
    )
    platform_helpers = (
        """
std::filesystem::path executable_path() {
    std::wstring value(32768, L'\\0');
    const auto length = GetModuleFileNameW(nullptr, value.data(), static_cast<DWORD>(value.size()));
    if (length == 0 || length == value.size()) throw std::runtime_error("cannot resolve the BDS executable path");
    value.resize(length);
    return value;
}

void* executable_base() { return GetModuleHandleW(nullptr); }
"""
        if windows
        else """
std::filesystem::path executable_path() {
    std::array<char, 4096> value{};
    const auto length = readlink("/proc/self/exe", value.data(), value.size() - 1);
    if (length <= 0 || static_cast<std::size_t>(length) >= value.size()) {
        throw std::runtime_error("cannot resolve the BDS executable path");
    }
    return std::string(value.data(), static_cast<std::size_t>(length));
}

int find_main_image(dl_phdr_info* info, std::size_t, void* output) {
    if (info->dlpi_name == nullptr || info->dlpi_name[0] == '\\0') {
        *static_cast<void**>(output) = reinterpret_cast<void*>(info->dlpi_addr);
        return 1;
    }
    return 0;
}

void* executable_base() {
    void* result = nullptr;
    dl_iterate_phdr(find_main_image, &result);
    return result;
}
"""
    )
    text = f"""// Generated by sdkgen for one exact reviewed BDS executable. No proprietary code is included.
#include <onibridge/authentication_adapter.hpp>
#include <onibridge/config.hpp>
#include <onibridge/generated_adapter.hpp>
#include <onibridge/hooks.hpp>
#include <onibridge/operations.hpp>
#include <onibridge/service.hpp>

#include <array>
#include <cstddef>
#include <filesystem>
#include <stdexcept>
#include <string>

{platform_include}

namespace onistone::onibridge {{
namespace {{

constexpr char kProfileId[] = "{profile_id}";
constexpr char kExecutableHash[] = "{executable_hash}";
constexpr std::uint64_t kExecutableSize = {profile["executable_size"]}ULL;
constexpr bool kProductionProfile = {"true" if profile.get("validation_status") == "production" else "false"};
constexpr std::array<std::byte, 5> kExpectedCall{{{byte_values}}};
AuthenticationCallSiteAdapter adapter;

{platform_helpers}

}} // namespace

bool install_generated_native_login_hook(
    OniBridgeService& service,
    const OniBridgeConfig& config,
    CommandCompatibilityMonitor&,
    std::string& error) {{
    try {{
        if (config.required_profile != kProfileId) {{
            error = std::string("configured profile must exactly equal ") + kProfileId;
            return false;
        }}
        if (!kProductionProfile && !config.allow_unreviewed_profile) {{
            error = "selected profile is a candidate; allow_unreviewed_profile is required for non-production testing";
            return false;
        }}
        const auto fingerprint = BdsRuntimeDetector::inspect(executable_path());
        if (fingerprint.sha256 != kExecutableHash || fingerprint.size != kExecutableSize
            || fingerprint.architecture != "x86_64") {{
            error = "loaded BDS executable hash, size, or architecture differs from the generated profile";
            return false;
        }}
        const AuthenticationCallSiteSpec spec{{
            .call_rva = {_integer(profile, "target_rva")}ULL,
            .move_helper_rva = {_integer(profile, "target_call_destination_rva")}ULL,
            .native_string_size = {_integer(sizes, "std::string")},
            .authentication_info_size = {_integer(sizes, "PlayerAuthenticationInfo")},
            .xuid_offset = {_integer(offsets, "PlayerAuthenticationInfo.xuid")},
            .xbox_live_name_offset = {_integer(offsets, "PlayerAuthenticationInfo.xbox_live_name")},
            .best_display_name_offset = {_integer(offsets, "PlayerAuthenticationInfo.best_display_name")},
            .authenticated_uuid_offset = {_integer(offsets, "PlayerAuthenticationInfo.authenticated_uuid")},
            .optional_engaged_offset = {_integer(offsets, "optional<PlayerAuthenticationInfo>.engaged")},
            .expected_call_bytes = kExpectedCall.data(),
            .expected_call_bytes_size = kExpectedCall.size(),
        }};
        auto* base = executable_base();
        if (base == nullptr) {{
            error = "cannot resolve the loaded BDS executable base";
            return false;
        }}
        return adapter.install(base, spec, service, error);
    }} catch (const std::exception& exception) {{
        error = exception.what();
        return false;
    }}
}}

bool uninstall_generated_native_login_hook(std::string& error) {{ return adapter.uninstall(error); }}

}} // namespace onistone::onibridge
"""
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(text, encoding="utf-8")
