from __future__ import annotations

from pathlib import Path
from typing import Any

from .profile import ProfileError


TYPE_NAMES = (
    "ServerNetworkHandler", "NetworkIdentifier", "LoginPacket", "ConnectionRequest",
    "PlayerAuthenticationInfo", "PlayerStorageIds", "ServerPlayer", "Certificate",
    "SerializedSkin", "CommandOriginData", "CommandRequestPacket", "AvailableCommandsPacket",
    "UpdateSoftEnumPacket", "CommandOutputPacket",
)


def generate_minimal_header(abi: dict[str, Any], destination: Path) -> None:
    if abi.get("status") != "verified":
        raise ProfileError("ABI input is not verified")
    sizes = abi.get("sizes")
    alignments = abi.get("alignments")
    offsets = abi.get("offsets")
    if not all(isinstance(value, dict) for value in (sizes, alignments, offsets)):
        raise ProfileError("ABI sizes, alignments, and offsets must be objects")
    if "PlayerAuthenticationInfo" not in sizes or "PlayerAuthenticationInfo" not in alignments:
        raise ProfileError("verified ABI is missing PlayerAuthenticationInfo size or alignment")
    if not isinstance(offsets.get("PlayerAuthenticationInfo.xuid"), int):
        raise ProfileError("verified ABI is missing PlayerAuthenticationInfo.xuid offset")
    required_offsets = (
        "PlayerAuthenticationInfo.xbox_live_name",
        "PlayerAuthenticationInfo.best_display_name",
        "PlayerAuthenticationInfo.authenticated_uuid",
        "optional<PlayerAuthenticationInfo>.engaged",
    )
    if any(not isinstance(offsets.get(name), int) for name in required_offsets):
        raise ProfileError("verified ABI is missing a required authentication or optional offset")
    declarations = "\n".join(f"class {name};" for name in TYPE_NAMES)
    text = f"""// Generated by sdkgen. Minimal declarations only; no proprietary definitions.
#pragma once
#include <cstddef>
#include <cstdint>

namespace onistone::onibridge::bds {{
{declarations}

struct PlayerAuthenticationInfoLayout final {{
    static constexpr std::size_t verified_size = {sizes['PlayerAuthenticationInfo']};
    static constexpr std::size_t verified_alignment = {alignments['PlayerAuthenticationInfo']};
    static constexpr std::size_t xuid_offset = {offsets['PlayerAuthenticationInfo.xuid']};
    static constexpr std::size_t xbox_live_name_offset = {offsets['PlayerAuthenticationInfo.xbox_live_name']};
    static constexpr std::size_t best_display_name_offset = {offsets['PlayerAuthenticationInfo.best_display_name']};
    static constexpr std::size_t authenticated_uuid_offset = {offsets['PlayerAuthenticationInfo.authenticated_uuid']};
    static constexpr std::size_t optional_engaged_offset = {offsets['optional<PlayerAuthenticationInfo>.engaged']};
}};

static_assert(PlayerAuthenticationInfoLayout::xuid_offset < PlayerAuthenticationInfoLayout::verified_size);
static_assert(PlayerAuthenticationInfoLayout::best_display_name_offset < PlayerAuthenticationInfoLayout::verified_size);
static_assert(PlayerAuthenticationInfoLayout::optional_engaged_offset == PlayerAuthenticationInfoLayout::verified_size);
}} // namespace onistone::onibridge::bds
"""
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(text, encoding="utf-8")
