from __future__ import annotations

import argparse
import base64
from dataclasses import dataclass
from datetime import datetime, timezone
import json
import os
from pathlib import Path
import re
import secrets
import ssl
import stat
import sys
from typing import Any
from urllib import error, parse, request
import zipfile


TENANT_PATTERN = re.compile(r"[a-z][a-z0-9-]{1,31}")
API_KEY_ENV = "PTERODACTYL_APPLICATION_API_KEY"
API_ACCEPT = "Application/vnd.pterodactyl.v1+json"
PLAN_VERSION = 1


class TenantError(RuntimeError):
    pass


class PterodactylApiError(TenantError):
    def __init__(self, status_code: int, detail: str) -> None:
        super().__init__(f"Pterodactyl API returned HTTP {status_code}: {detail}")
        self.status_code = status_code


@dataclass(frozen=True)
class Endpoint:
    host: str
    port: int

    @property
    def display(self) -> str:
        host = f"[{self.host}]" if ":" in self.host else self.host
        return f"{host}:{self.port}"


def parse_endpoint(value: str, label: str) -> Endpoint:
    value = value.strip()
    if value.startswith("["):
        closing = value.find("]")
        if closing < 2 or closing + 2 >= len(value) or value[closing + 1] != ":":
            raise TenantError(f"{label} IPv6 addresses must use [address]:port")
        host = value[1:closing]
        port_text = value[closing + 2 :]
    else:
        if value.count(":") != 1:
            raise TenantError(f"{label} must use host:port")
        host, port_text = value.rsplit(":", 1)
    if not host or any(character.isspace() for character in host):
        raise TenantError(f"{label} has an invalid host")
    try:
        port = int(port_text)
    except ValueError as exception:
        raise TenantError(f"{label} port must be a number") from exception
    if not 1 <= port <= 65_535:
        raise TenantError(f"{label} port must be 1..65535")
    return Endpoint(host, port)


def exact_cidr(address: str) -> str:
    import ipaddress

    try:
        parsed = ipaddress.ip_address(address)
    except ValueError as exception:
        raise TenantError(
            "proxy source IP must be a numeric IPv4 or IPv6 address"
        ) from exception
    return f"{parsed.compressed}/{parsed.max_prefixlen}"


def load_settings(path: Path) -> dict[str, Any]:
    try:
        settings = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exception:
        raise TenantError(
            f"cannot read tenant settings from {path}: {exception}"
        ) from exception
    required = (
        "panel_url",
        "egg_id",
        "docker_image",
        "startup",
        "onilink_version",
        "plans",
    )
    missing = [key for key in required if key not in settings]
    if missing:
        raise TenantError(f"tenant settings are missing: {', '.join(missing)}")
    panel_url = str(settings["panel_url"]).rstrip("/")
    if not panel_url.startswith("https://"):
        raise TenantError("panel_url must use HTTPS")
    settings["panel_url"] = panel_url
    if not isinstance(settings["plans"], dict) or not settings["plans"]:
        raise TenantError("plans must be a non-empty object")
    return settings


def validate_tenant(value: str) -> str:
    tenant = value.strip().lower()
    if not TENANT_PATTERN.fullmatch(tenant):
        raise TenantError(
            "tenant must be 2..32 lowercase letters, numbers, or hyphens and start with a letter"
        )
    return tenant


def random_forwarding_secret() -> str:
    return base64.b64encode(secrets.token_bytes(32)).decode("ascii")


def onibridge_toml(profile: str, trusted_proxy_cidr: str) -> str:
    return f'''# Generated by OniLink tenantctl for the isolated default backend.
# Install as: /home/container/plugins/onibridge/onibridge.toml

bridge_id = "default-main"
backend_name = "default"
trusted_proxy_cidrs = ["{trusted_proxy_cidr}"]
shutdown_on_hook_failure = true
reject_direct_joins = true

[forwarding]
protocol = 2
active_key_id = "key-1"
active_secret_env = ""
active_secret_file = "default.key"
previous_key_id = ""
previous_secret_env = ""
previous_secret_file = ""
maximum_token_size = 4096
maximum_lifetime_ms = 10000
allowed_clock_skew_ms = 2000
replay_cache_max_entries = 10000

[identity]
uuid_mode = "preserve_backend"
verify_post_login_xuid = true
store_verified_identities = true

[commands]
register_native_commands = true
command_namespace = "onibridge"
interfere_with_backend_commands = false

[compatibility]
required_profile = "{profile}"
allow_unreviewed_profile = false
allow_unknown_bds = false
allow_unknown_endstone = false

[legacy_verification]
enabled = false
'''


def build_plan(
    settings: dict[str, Any],
    *,
    tenant: str,
    user_id: int,
    allocation_id: int,
    proxy: Endpoint,
    backend: Endpoint,
    proxy_source_ip: str,
    plan_name: str,
) -> dict[str, Any]:
    tenant = validate_tenant(tenant)
    if user_id < 1:
        raise TenantError("user ID must be a positive Pterodactyl user ID")
    if allocation_id < 1:
        raise TenantError("allocation ID must be a positive Pterodactyl allocation ID")
    plans = settings["plans"]
    if plan_name not in plans:
        raise TenantError(
            f"unknown plan '{plan_name}'; choose one of: {', '.join(sorted(plans))}"
        )
    limits = plans[plan_name]
    if not isinstance(limits, dict):
        raise TenantError(f"plan '{plan_name}' must be an object")
    missing_limits = [name for name in ("memory", "disk", "cpu") if name not in limits]
    if missing_limits:
        raise TenantError(f"plan '{plan_name}' is missing: {', '.join(missing_limits)}")
    forwarding_secret = random_forwarding_secret()
    setup_code = secrets.token_urlsafe(24)
    trusted_proxy_cidr = exact_cidr(proxy_source_ip)
    max_players = int(limits.get("max_players", 20))
    server_request = {
        "external_id": f"onilink-tenant-{tenant}",
        "name": f"OniLink - {tenant}",
        "description": f"Isolated OniLink proxy instance for tenant {tenant}.",
        "user": user_id,
        "egg": int(settings["egg_id"]),
        "docker_image": str(settings["docker_image"]),
        "startup": str(settings["startup"]),
        "environment": {
            "ONILINK_VERSION": str(settings["onilink_version"]),
            "SERVER_JARFILE": "OniLink.jar",
            "CONFIG_FILE": "config.properties",
            "DASHBOARD_ENABLED": "true",
            "ALLOWLIST_ENABLED": "false",
            "BACKEND_HOST": backend.host,
            "BACKEND_PORT": str(backend.port),
            "SERVER_MOTD": f"{tenant} Network",
            "MAX_PLAYERS": str(max_players),
            "ONIBRIDGE_FORWARDING_SECRET": forwarding_secret,
            "ONIBRIDGE_SURVIVAL_SECRET": "",
            "ONIBRIDGE_JAVA_SECRET": "",
            "ONILINK_DASHBOARD_SETUP_CODE": setup_code,
        },
        "limits": {
            "memory": int(limits["memory"]),
            "swap": int(limits.get("swap", 0)),
            "disk": int(limits["disk"]),
            "io": int(limits.get("io", 500)),
            "cpu": int(limits["cpu"]),
            "threads": limits.get("threads"),
        },
        "feature_limits": {
            "databases": int(limits.get("databases", 0)),
            "allocations": 0,
            "backups": int(limits.get("backups", 1)),
        },
        "allocation": {"default": allocation_id},
        "skip_scripts": False,
        "oom_disabled": False,
    }
    return {
        "schema_version": PLAN_VERSION,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "tenant": tenant,
        "plan": plan_name,
        "isolation": "dedicated-pterodactyl-server",
        "proxy_address": proxy.display,
        "backend_address": backend.display,
        "trusted_proxy_cidr": trusted_proxy_cidr,
        "server_request": server_request,
        "handoff": {
            "dashboard_url": f"http://{proxy.display}/",
            "dashboard_setup_code": setup_code,
            "forwarding_secret": forwarding_secret,
            "onibridge_toml": onibridge_toml(
                str(
                    settings.get(
                        "bds_profile", "bds-1.26.44.3-linux-x86_64-06effdd00067f1ae"
                    )
                ),
                trusted_proxy_cidr,
            ),
        },
    }


def secure_write(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        raise TenantError(f"refusing to replace existing sensitive file: {path}")
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    descriptor = os.open(path, flags, stat.S_IRUSR | stat.S_IWUSR)
    try:
        with os.fdopen(descriptor, "wb") as output:
            output.write(content)
    except Exception:
        try:
            path.unlink()
        except OSError:
            pass
        raise


def write_handoff(path: Path, plan: dict[str, Any]) -> None:
    handoff = plan["handoff"]
    instructions = f"""ONILINK TENANT HANDOFF

Tenant: {plan["tenant"]}
Isolation: one dedicated Pterodactyl server; no other tenant backends are present.
Player address: {plan["proxy_address"]}
Dashboard: {handoff["dashboard_url"]}
One-time dashboard setup code: {handoff["dashboard_setup_code"]}

PORTS
- The OniLink server uses one primary allocation. UDP is the Bedrock listener and TCP is the
  dashboard on the same numeric port.
- The BDS server keeps its own UDP allocation: {plan["backend_address"]}
- OniBridge needs no additional allocation.

BACKEND INSTALL
1. Install the matching OniBridge .so in /home/container/plugins/ on the tenant's BDS server.
2. Upload backend/default.key and backend/onibridge.toml from this ZIP into:
   /home/container/plugins/onibridge/
3. Start BDS and confirm the native identity hook is active.
4. Start OniLink and use the setup code above to create the tenant's dashboard owner.

Treat this ZIP as a secret. It contains the backend forwarding key and setup code.
"""
    from io import BytesIO

    archive = BytesIO()
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as output:
        output.writestr("CUSTOMER-START-HERE.txt", instructions)
        output.writestr("backend/default.key", handoff["forwarding_secret"] + "\n")
        output.writestr("backend/onibridge.toml", handoff["onibridge_toml"])
    secure_write(path, archive.getvalue())


class PterodactylClient:
    def __init__(self, panel_url: str, api_key: str) -> None:
        if not api_key:
            raise TenantError(f"{API_KEY_ENV} is not set")
        self.panel_url = panel_url.rstrip("/")
        self.api_key = api_key
        self.context = ssl.create_default_context()

    def call(
        self, method: str, path: str, payload: dict[str, Any] | None = None
    ) -> Any:
        body = None if payload is None else json.dumps(payload).encode("utf-8")
        api_request = request.Request(
            self.panel_url + "/api/application" + path,
            data=body,
            method=method,
            headers={
                "Accept": API_ACCEPT,
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
                "User-Agent": "OniLink-tenantctl/1",
            },
        )
        try:
            with request.urlopen(
                api_request, context=self.context, timeout=30
            ) as response:
                content = response.read()
                return json.loads(content) if content else None
        except error.HTTPError as exception:
            detail = exception.read().decode("utf-8", errors="replace")[:2_000]
            raise PterodactylApiError(exception.code, detail) from exception
        except error.URLError as exception:
            raise TenantError(
                f"cannot reach the Pterodactyl API: {exception.reason}"
            ) from exception

    def find_tenant(self, tenant: str) -> dict[str, Any] | None:
        external_id = parse.quote(f"onilink-tenant-{validate_tenant(tenant)}", safe="")
        try:
            result = self.call("GET", f"/servers/external/{external_id}")
        except PterodactylApiError as exception:
            if exception.status_code == 404:
                return None
            raise
        return result["attributes"]

    def create(self, server_request: dict[str, Any]) -> dict[str, Any]:
        result = self.call("POST", "/servers", server_request)
        return result["attributes"]

    def set_suspended(self, server_id: int, suspended: bool) -> None:
        action = "suspend" if suspended else "unsuspend"
        self.call("POST", f"/servers/{server_id}/{action}", {})


def prepare(args: argparse.Namespace) -> int:
    settings = load_settings(args.config)
    proxy = parse_endpoint(args.proxy_address, "proxy address")
    backend = parse_endpoint(args.backend_address, "backend address")
    source_ip = args.proxy_source_ip or proxy.host
    plan = build_plan(
        settings,
        tenant=args.tenant,
        user_id=args.user_id,
        allocation_id=args.allocation_id,
        proxy=proxy,
        backend=backend,
        proxy_source_ip=source_ip,
        plan_name=args.plan,
    )
    target = args.output_directory.resolve()
    plan_path = target / f"{plan['tenant']}.provision.json"
    handoff_path = target / f"{plan['tenant']}.handoff.zip"
    secure_write(plan_path, (json.dumps(plan, indent=2) + "\n").encode("utf-8"))
    try:
        write_handoff(handoff_path, plan)
    except Exception:
        plan_path.unlink(missing_ok=True)
        raise
    print(f"prepared isolated tenant {plan['tenant']}")
    print(f"private plan: {plan_path}")
    print(f"customer handoff: {handoff_path}")
    print("The plan and handoff contain secrets; transmit and retain them securely.")
    return 0


def read_plan(path: Path) -> dict[str, Any]:
    try:
        plan = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exception:
        raise TenantError(
            f"cannot read provision plan {path}: {exception}"
        ) from exception
    if plan.get("schema_version") != PLAN_VERSION:
        raise TenantError("unsupported provision plan version")
    validate_tenant(str(plan.get("tenant", "")))
    server_request = plan.get("server_request")
    if not isinstance(server_request, dict):
        raise TenantError("provision plan has no server_request")
    tenant = str(plan["tenant"])
    if server_request.get("external_id") != f"onilink-tenant-{tenant}":
        raise TenantError("provision plan external ID does not match its tenant")
    allocation = server_request.get("allocation")
    if not isinstance(allocation, dict) or set(allocation) != {"default"}:
        raise TenantError("tenant plans must assign exactly one primary allocation")
    if not isinstance(allocation["default"], int) or allocation["default"] < 1:
        raise TenantError("tenant plan primary allocation ID must be positive")
    feature_limits = server_request.get("feature_limits")
    if not isinstance(feature_limits, dict) or feature_limits.get("allocations") != 0:
        raise TenantError("tenant plans may not grant additional allocations")
    return plan


def client(settings: dict[str, Any]) -> PterodactylClient:
    return PterodactylClient(settings["panel_url"], os.environ.get(API_KEY_ENV, ""))


def apply_plan(args: argparse.Namespace) -> int:
    settings = load_settings(args.config)
    plan = read_plan(args.plan_file)
    api = client(settings)
    existing = api.find_tenant(plan["tenant"])
    if existing is not None:
        print(
            f"tenant {plan['tenant']} already exists as Pterodactyl server {existing['id']}"
        )
        return 0
    created = api.create(plan["server_request"])
    print(
        f"created isolated tenant {plan['tenant']} as Pterodactyl server {created['id']}"
    )
    print(f"player address: {plan['proxy_address']}")
    return 0


def status(args: argparse.Namespace) -> int:
    settings = load_settings(args.config)
    tenant = validate_tenant(args.tenant)
    existing = client(settings).find_tenant(tenant)
    if existing is None:
        print(f"tenant {tenant} does not exist")
        return 1
    print(
        json.dumps(
            {
                "tenant": tenant,
                "server_id": existing.get("id"),
                "uuid": existing.get("uuid"),
                "suspended": existing.get("suspended", False),
                "status": existing.get("status"),
            },
            indent=2,
        )
    )
    return 0


def set_billing_state(args: argparse.Namespace, suspended: bool) -> int:
    settings = load_settings(args.config)
    tenant = validate_tenant(args.tenant)
    api = client(settings)
    existing = api.find_tenant(tenant)
    if existing is None:
        raise TenantError(f"tenant {tenant} does not exist")
    api.set_suspended(int(existing["id"]), suspended)
    state = "suspended" if suspended else "active"
    print(f"tenant {tenant} is now {state}")
    return 0


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(
        description="Provision one isolated OniLink Pterodactyl server per paying tenant."
    )
    commands = root.add_subparsers(dest="command", required=True)

    prepare_parser = commands.add_parser(
        "prepare", help="create a private plan and customer handoff ZIP"
    )
    prepare_parser.add_argument("--config", type=Path, required=True)
    prepare_parser.add_argument("--tenant", required=True)
    prepare_parser.add_argument("--user-id", type=int, required=True)
    prepare_parser.add_argument("--allocation-id", type=int, required=True)
    prepare_parser.add_argument(
        "--proxy-address", required=True, help="public player address as IP:port"
    )
    prepare_parser.add_argument(
        "--proxy-source-ip", help="numeric IP that BDS sees; defaults to proxy host"
    )
    prepare_parser.add_argument(
        "--backend-address", required=True, help="tenant BDS allocation as host:port"
    )
    prepare_parser.add_argument("--plan", default="starter")
    prepare_parser.add_argument(
        "--output-directory", type=Path, default=Path("tenant-output")
    )
    prepare_parser.set_defaults(handler=prepare)

    apply_parser = commands.add_parser(
        "apply", help="idempotently create the prepared server"
    )
    apply_parser.add_argument("--config", type=Path, required=True)
    apply_parser.add_argument("--plan-file", type=Path, required=True)
    apply_parser.set_defaults(handler=apply_plan)

    for name, help_text in (
        ("status", "show the Pterodactyl server linked to a tenant"),
        ("suspend", "suspend a tenant after a billing decision"),
        ("unsuspend", "restore a tenant after a billing decision"),
    ):
        command = commands.add_parser(name, help=help_text)
        command.add_argument("--config", type=Path, required=True)
        command.add_argument("--tenant", required=True)
        if name == "status":
            command.set_defaults(handler=status)
        else:
            command.set_defaults(
                handler=lambda args, value=name == "suspend": set_billing_state(
                    args, value
                )
            )
    return root


def main(argv: list[str] | None = None) -> int:
    try:
        args = parser().parse_args(argv)
        return int(args.handler(args))
    except TenantError as exception:
        print(f"tenantctl: {exception}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
